#!/bin/sh
set -ux

# TODO: Link these explicit system calls against the layer.yaml configuration
systemctl status snap.etcd.etcd > $DEBUG_SCRIPT_DIR/etcd-systemctl-status
journalctl -u snap.etcd.etcd > $DEBUG_SCRIPT_DIR/etcd-journal

alias etcdctl="/snap/bin/etcd.etcdctl --cert-file /var/snap/etcd/common/client.crt --key-file /var/snap/etcd/common/client.key --ca-file /var/snap/etcd/common/ca.crt"
etcdctl cluster-health > $DEBUG_SCRIPT_DIR/etcdctl-cluster-health
etcdctl ls --recursive > $DEBUG_SCRIPT_DIR/etcdctl-ls
etcdctl member list > $DEBUG_SCRIPT_DIR/etcdctl-member-list
