#!/bin/bash

set -e
PRIVATE_ADDRESS=$(unit-get private-address)
PORT=$(unit-get port)
OUT=$(/usr/bin/etcdctl -C http://${PRIVATE_ADDRESS}:${PORT} cluster-health)

action-set result-map.message="${OUT}"
