#!/bin/bash

# The certificates live in leader-data. Grab them from there, always

mkdir -p etcd_credentials

leader-get client_certificate > etcd_credentials/clientcert.pem
leader-get client_key > etcd_credentials/clientkey.pem
leader-get certificate_authority > etcd_credentials/ca.pem

# Render a README heredoc
cat << EOF > etcd_credentials/README.txt
# ETCD Credentials Package

Greetings! This credentials package was generated for you by Juju. In order
to consume these keys, you will need to do a few things first:

Untarball the archive somewhere you wish to keep your sensitive client
credentials.

Export those locations as environment variables, set the etcdctl endpoint,
and expose the etcd service. Even though Etcd is currently configured to
validate SSL certificates before a connection can be established, it's best
practice to leave it firewalled from the world unless you have need of an
exposed etcd endpoint.

  juju expose etcd
  export ETCDCTL_KEY_FILE=$(pwd)/clientkey.pem
  export ETCDCTL_CERT_FILE=$(pwd)/clientcert.pem
  export ETCDCTL_CA_FILE=$(pwd)/ca.pem
  export ETCDCTL_ENDPOINT=https://{ip of etcd host}:2379
  etcdctl member list

If you have any trouble regarding connecting to your Etcd cluster, don't
hesitate to reach out over the juju mailing list: juju@lists.ubuntu.com

EOF

tar cfz etcd_credentials.tar.gz etcd_credentials
cp etcd_credentials.tar.gz /home/ubuntu/
