name: Charmed Kubernetes Integration Tests
on: 
  - pull_request

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    strategy:
      matrix:
        series:
        - jammy
        - noble
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.10"
      - id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@ea90ed489690bf3b1c1fcca6ac5f9edab70aecb0 # main
        with:
          provider: lxd
          juju-channel: 3/stable
          charm-channel: 3.x/stable
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
          bootstrap-options: "--bootstrap-base=ubuntu@24.04"
      - name: Run test
        run: tox -e integration -- --series ${{ matrix.series }}
      - name: Setup Debug Artifact Collection
        if: ${{ failure() }}
        run: mkdir tmp
      - name: Collect Juju Status
        if: ${{ failure() }}
        run: |
          cat $HOME/.local/state/charmcraft/log/*.log | tee tmp/charmcraft.log
          juju status 2>&1 | tee tmp/juju-status.txt
          juju-crashdump -s -m controller -a debug-layer -a config -o tmp/
          mv juju-crashdump-* tmp/ | true
      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-run-artifacts
          path: tmp
